---
application:
  name: "jualair"
  project: "jualaer-210608"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "jualair"
  version: "10"
routers:
- name: "main-jualair"
  routes:
  - application_name: "jualair"
    paths:
    - "/*"
